#eureka:
#  instance:
  #注册服务IP，而不是服务器名称
#    preferIpAddress: true
#  client:
  #向Eureka注册服务
#    registerWitEureka: true
    #拉取注册表的本地副本
#    fetchRegistry: true
#    serviceUrl:
    #Eureka服务的位置
#      defaultZone: http://localhost:8761/eureka/