#Eureka服务器将要监听的端口
server:
  port: 8761

eureka:
  client:
  #不要使用Eureka服务进行注册
    registerWithEureka: false
    #不要在本地缓存注册表信息
  fetchRegistry: false
  server:
  #在服务器接收请求之前等待初始时间
    waitTimeInMsWhenSyncEmpty: 5