example.property: "I AM IN THE DEFAULT"
spring.jpa.database: "H2SQL"
spring.datasource.platform:  "h2"
spring.jpa.show-sql: "true"
spring.database.driverClassName: "org.h2.Driver"
spring.datasource.url: "jdbc:h2:mem:h2test;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE"
spring.datasource.username: "gbs"
spring.datasource.password: "{cipher}4788dfe1ccbe6485934aec2ffeddb06163ea3d616df5fd75be96aadd4df1da91"
spring.datasource.testWhileIdle: "true"
spring.datasource.validationQuery: "SELECT 1"
spring.jpa.properties.hibernate.dialect: "org.hibernate.dialect.PostgreSQLDialect"
redis.server: "redis"
redis.port: "6379"
signing.key: "345345fsdfsf5345"