spring:
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/config/licensingservice,classpath:/config/organizationservice
server:
  port: 8888